USE [TCC.DB]
GO

/****** Object:  Table [dbo].[TCC_USER]    Script Date: 20/04/2019 21:19:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TCC_USER](
	[ID_N] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[NAME_C] [varchar](50) NOT NULL,
	[EMAIL_C] [varchar](250) NOT NULL,
	[PASSWORD_C] [nchar](150) NOT NULL,
	[ADDED_DATE_D] [datetime] NOT NULL,
	[MODIFIED_DATE_D] [datetime] NULL,
	[ACTIVE_B] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_N] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


